version: '2'

services:
    nodeapp:
        container_name : node-app
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - './app/:/app'
            - /app/node_modules
        ports:
            - "9090:5000"
        networks:
            - my-app-net
        env_file:
            - ./.env
    redis:
        image: redislabs/redisearch
        volumes:
            - /home/redis_data:/data
        networks:
            - my-app-net

networks:
    my-app-net:
        driver: bridge
        ipam:
            config:
            - subnet: "20.1.0.0/16"
